on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest 


    steps:
  

      - name: "Login to Docjer Hub"
        run: pwd
      - name: "Building docker image"
        run: echo ahmed
      
    