on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest 


    steps:
      - uses: actions/checkout@v3

      - name: "Login to Docjer Hub"
        run: docker login --username mahmoud2992002 --password dckr_pat_mI3L2096u4dweFAb_jxJ8f-LgAI
      - name: "vvvv"
        run: echo ahmed
      
    