on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest 


    steps:
  
      build:
        runs-on: ubuntu-latest


        steps:
          - name: 'testing git hub action'
            run: pwd

          - name: 'testing princing'
            run: echo Ahmed
